(()=>{
 if(document.querySelector('#retoma-launcher'))return;
 const launcher=document.createElement('button');launcher.id='retoma-launcher';launcher.textContent='Retoma';document.body.appendChild(launcher);
 const escape=value=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 function contact(){const header=document.querySelector('#main header');const titled=[...(header?.querySelectorAll('[title]')||[])].map(e=>e.getAttribute('title')?.trim()).find(Boolean);return titled||header?.querySelector('span')?.textContent?.trim()||'';}
 function transcript(){const main=document.querySelector('#main');if(!main)return [];const nodes=[...main.querySelectorAll('[data-id], [data-testid="msg-container"]')];const seen=new Set(),items=[];for(const node of nodes){const text=[...node.querySelectorAll('.selectable-text, [data-testid="msg-text"]')].map(e=>e.textContent?.trim()).filter(Boolean).join('\n').trim();if(!text)continue;const role=node.closest('.message-out')||node.matches('.message-out')?'vendedor':node.closest('.message-in')||node.matches('.message-in')?'cliente':node.getAttribute('data-id')?.includes('true_')?'vendedor':'cliente';const key=role+'\0'+text+'\0'+items.length;if(seen.has(key))continue;seen.add(key);items.push({role,text});}return items.slice(-40);}
 function panel(){const name=contact();const el=document.createElement('aside');el.id='retoma-panel';el.innerHTML=`<header><span>R</span><div><b>Retoma</b><small>${escape(name||'Abra uma conversa')}</small></div><button type="button" aria-label="Fechar">×</button></header><main><div class="notice">A extensão lê somente as mensagens carregadas na conversa aberta quando você clicar em analisar.</div><label>Assunto do orçamento<input id="retoma-subject" maxlength="160" placeholder="Ex.: fachada em ACM"></label><label class="check"><input id="retoma-consent" type="checkbox"><span>Confirmo que este contato autorizou o atendimento e que posso usar esta conversa no teste.</span></label><button class="primary" id="retoma-analyze">Analisar e sugerir resposta</button><output class="status" id="retoma-status"></output><div id="retoma-result"></div><button class="secondary" id="retoma-pause">Pausar IA nesta conversa</button><p class="privacy">Nenhuma mensagem é enviada automaticamente. Revise a sugestão e use Copiar resposta.</p></main>`;document.body.appendChild(el);launcher.hidden=true;el.querySelector('header button').onclick=()=>{el.remove();launcher.hidden=false;};
  const status=el.querySelector('#retoma-status'),result=el.querySelector('#retoma-result'),analyze=el.querySelector('#retoma-analyze');
  analyze.onclick=async()=>{const current=contact(),messages=transcript();if(!current){status.textContent='Abra uma conversa no WhatsApp Web.';return;}if(!el.querySelector('#retoma-consent').checked){status.textContent='Confirme a autorização antes de continuar.';return;}analyze.disabled=true;status.textContent=`Lendo ${messages.length} mensagens visíveis e consultando a assistente…`;result.innerHTML='';const payload={mode:'analyze',requestId:crypto.randomUUID(),contactKey:current,contactName:current,subject:el.querySelector('#retoma-subject').value.trim(),consent:true,messages};chrome.runtime.sendMessage({type:'retoma-api',payload},response=>{analyze.disabled=false;if(chrome.runtime.lastError||!response?.ok){status.textContent=response?.error||chrome.runtime.lastError?.message||'Não foi possível consultar o Retoma.';return;}const data=response.data;status.textContent='Sugestão pronta para revisão.';result.innerHTML=`<section class="result">${data.needsHuman?`<div class="alert"><b>Vendedor necessário:</b> ${escape(data.reason)}</div>`:''}<h3>Resumo</h3><p>${escape(data.summary)}</p><h3>Resposta sugerida</h3><textarea rows="7" id="retoma-suggestion">${escape(data.suggestion)}</textarea><button class="primary" id="retoma-copy">Copiar resposta</button></section>`;result.querySelector('#retoma-copy').onclick=async()=>{await navigator.clipboard.writeText(result.querySelector('#retoma-suggestion').value);status.textContent='Resposta copiada. Revise e cole no WhatsApp.';};});};
  el.querySelector('#retoma-pause').onclick=()=>{const current=contact();if(!current){status.textContent='Abra uma conversa no WhatsApp Web.';return;}chrome.runtime.sendMessage({type:'retoma-api',payload:{mode:'pause',contactKey:current,contactName:current}},response=>{status.textContent=response?.ok?'IA pausada nesta conversa.':response?.error||'Não foi possível pausar.';});};
 }
 launcher.addEventListener('click',panel);
})();
