import {db,load,commit,readBody,AppError} from '../../../server/store';
import {generate,mandatory} from '../../../server/gemini';
import {validateDecision} from '../../../server/decisions';
import {business} from '../../../business-model';
import {cleanImportedMessages,mergeImportedMessages} from '../../../extension-model';
import {recordInterests} from '../../../conversation-tools';
import {terminal,type Lead} from '../../../recovery-model';

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Cache-Control':'no-store'};
const respond=(data:unknown,status=200)=>Response.json(data,{status,headers:cors});
const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(b=>b.toString(16).padStart(2,'0')).join('');
async function authenticate(req:Request){const match=req.headers.get('authorization')?.match(/^Bearer (rtm_[a-f0-9]{64})$/);if(!match)throw new AppError(401,'Vincule a extensão ao Retoma.');const row=await db().prepare('SELECT owner FROM extension_links WHERE token_hash=? AND revoked=0').bind(await hash(match[1])).first<{owner:string}>();if(!row)throw new AppError(401,'Vínculo inválido ou revogado.');await db().prepare('UPDATE extension_links SET last_used=? WHERE owner=?').bind(Date.now(),row.owner).run();return row.owner;}
export async function OPTIONS(){return new Response(null,{status:204,headers:cors})}
export async function POST(req:Request){let owner='',eventId='';try{
 owner=await authenticate(req);const body=await readBody(req);const mode=body.mode==='pause'?'pause':'analyze';
 if(typeof body.contactKey!=='string'||!body.contactKey.trim()||body.contactKey.length>200||typeof body.contactName!=='string'||!body.contactName.trim()||body.contactName.length>200)throw new AppError(400,'Abra uma conversa válida no WhatsApp Web.');
 const externalId='whatsapp-web:'+body.contactKey.trim();let snapshot=await load(owner);let lead=snapshot.data.leads.find(l=>l.externalId===externalId);
 if(mode==='pause'){if(!lead)throw new AppError(404,'Esta conversa ainda não está sendo acompanhada.');lead.ai=false;lead.needsHuman=false;lead.due='Ação do vendedor';lead.history=[...lead.history,'Vendedor pausou a IA pelo WhatsApp Web.'];await commit(owner,snapshot.revision,snapshot.data);return respond({paused:true});}
 if(body.consent!==true)throw new AppError(400,'Confirme a autorização antes de analisar.');const items=cleanImportedMessages(body.messages);if(!items.length)throw new AppError(400,'Nenhuma mensagem legível foi encontrada na conversa aberta.');
 const lastCustomer=[...items].reverse().find(m=>m.role==='cliente');if(!lastCustomer)throw new AppError(400,'A conversa não possui uma mensagem recebida para responder.');
 if(!lead){if(snapshot.data.leads.length>=100)throw new AppError(409,'Limite de acompanhamentos atingido.');const id=Math.max(0,...snapshot.data.leads.map(l=>l.id))+1;lead={id,externalId,name:body.contactName.trim(),company:'',service:typeof body.subject==='string'&&body.subject.trim()?body.subject.trim().slice(0,160):'Conversa do WhatsApp',value:null,date:new Date().toISOString().slice(0,10),status:'Conversando',ai:true,consent:true,optOut:false,due:'Em conversa',attempts:0,reason:'',needsHuman:false,notes:'Conversa importada pela extensão, com autorização do vendedor.',messages:[],history:['Acompanhamento criado pela extensão do Retoma.'],interests:[],events:[{id:crypto.randomUUID(),at:new Date().toISOString(),status:'Conversando',value:null,confirmed:false}]};snapshot.data.leads.push(lead);snapshot=await commit(owner,snapshot.revision,snapshot.data);}
 if(lead.optOut||terminal(lead))throw new AppError(409,'Este acompanhamento está encerrado e não pode ser reativado pela extensão.');if(business(snapshot.data.config).paused)throw new AppError(409,'A IA está em pausa geral no Retoma.');
 const recent=await db().prepare('SELECT COUNT(*) AS n FROM events WHERE owner=? AND created>?').bind(owner,Date.now()-60000).first<{n:number}>();if((recent?.n||0)>=6)throw new AppError(429,'Limite de testes atingido. Aguarde um minuto.');eventId=typeof body.requestId==='string'&&/^[a-zA-Z0-9-]{16,80}$/.test(body.requestId)?body.requestId:crypto.randomUUID();
 const created=await db().prepare("INSERT OR IGNORE INTO events(owner,id,lead_id,request,status,created) VALUES(?,?,?,?,'processing',?)").bind(owner,eventId,lead.id,JSON.stringify({source:'extension',externalId}),Date.now()).run();if(!created.meta.changes)throw new AppError(409,'Esta análise já está em processamento.');
 const at=new Date().toISOString();lead=mergeImportedMessages(lead,items,at);lead={...lead,name:body.contactName.trim(),ai:true,consent:true,status:'Conversando',due:'Sugestão pronta',interests:recordInterests(lead,snapshot.data.config,lastCustomer.text,eventId,at)};snapshot.data.leads=snapshot.data.leads.map(l=>l.id===lead!.id?lead!:l);snapshot=await commit(owner,snapshot.revision,snapshot.data);
 const forced=mandatory(lastCustomer.text);const decision=forced||validateDecision(snapshot.data.config,lead,lastCustomer.text,await generate(snapshot.data.config,lead,lastCustomer.text,'reply'));
 const latest=await load(owner),current=latest.data.leads.find(l=>l.id===lead!.id);if(!current||!current.ai||business(latest.data.config).paused)throw new AppError(409,'A IA foi pausada antes de concluir a sugestão.');
 const stop=decision.action==='stop',needsHuman=!stop&&(current.needsHuman||decision.action==='handoff');const reason=needsHuman?decision.reason:'';const next:Lead={...current,ai:!stop,optOut:stop,recoveryPaused:stop||needsHuman,needsHuman,reason,status:stop?'Encerrado':'Conversando',due:stop?'Não contatar':needsHuman?'Ação do vendedor · IA disponível':'Sugestão pronta',aiSummary:decision.summary,history:[...current.history,stop?'Pedido de interrupção identificado pela extensão.':needsHuman?'Sugestão preparada e vendedor alertado pela extensão.':'Sugestão preparada pela extensão; nenhum envio automático foi realizado.']};latest.data.leads=latest.data.leads.map(l=>l.id===next.id?next:l);await commit(owner,latest.revision,latest.data);await db().prepare("UPDATE events SET status='done',result=? WHERE owner=? AND id=?").bind(JSON.stringify({action:decision.action}),owner,eventId).run();return respond({suggestion:decision.text,summary:decision.summary,needsHuman,reason,stop,assistant:latest.data.config.assistant});
 }catch(e){if(owner&&eventId)await db().prepare("UPDATE events SET status='failed',result=? WHERE owner=? AND id=? AND status='processing'").bind(JSON.stringify({error:e instanceof AppError?e.status:500}),owner,eventId).run().catch(()=>{});return respond({error:e instanceof AppError?e.message:'Não foi possível preparar a resposta.'},e instanceof AppError?e.status:500)}}
