'use client';
import { useState } from 'react';
import { BookOpen, Sparkles, ShieldCheck, ArrowUpRight, Plus, Pencil, Check, FlaskConical, MessageSquareText, Building2, Clock3, SlidersHorizontal, Save, GraduationCap, Lightbulb, ArrowRight } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Switch } from '@/components/ui/switch';
import { toast } from '@/components/ui/toast';
import { replyTo, type Config, type Knowledge } from './recovery-model';

export function School({config,onSave,onConfigure}:{config:Config;onSave:(config:Config)=>void;onConfigure:()=>void}){
 const [question,setQuestion]=useState('Vocês fazem instalação?'),[result,setResult]=useState<ReturnType<typeof replyTo>|null>(null),[testedQuestion,setTestedQuestion]=useState(''),[correction,setCorrection]=useState(''),[editing,setEditing]=useState<Knowledge|null>(null),[open,setOpen]=useState(false),[approved,setApproved]=useState(false);
 function saveExample(q:string,a:string,id?:number){
  if(!q.trim()||!a.trim())return;
  const item={id:id??Date.now(),question:q.trim(),answer:a.trim()};
  onSave({...config,knowledge:id?config.knowledge.map(k=>k.id===id?item:k):[...config.knowledge,item],version:config.version+1});
  toast.add({title:'Exemplo aprovado',description:'Já pode ser testado nesta sessão. Nenhum modelo foi treinado.',type:'success'});
 }
 return <div className="content-page"><div className="page-title"><div><div className="eyebrow">CENTRAL DE CONHECIMENTO</div><h1>Uma IA que conhece seu negócio.</h1><p>Ensine com informações claras. Melhore com respostas aprovadas.</p></div><span className="version-tag"><span className="dot"/> Base v{config.version} · demonstração</span></div>
 <div className="school-intro"><div className="school-intro-copy"><span className="round-icon"><GraduationCap size={25}/></span><div><h2>Conhecimento, não adivinhação.</h2><p>A IA deve consultar o que sua empresa aprovou. Conversas de clientes não viram regras automaticamente.</p></div></div><button className="btn light" onClick={onConfigure}>Configurar meu negócio <ArrowUpRight size={17}/></button></div>
 <div className="learning-steps">{[[BookOpen,'01','Informe','Cadastre o que vende, o que não faz e suas condições.'],[FlaskConical,'02','Teste','Experimente as perguntas reais dos seus clientes.'],[Pencil,'03','Corrija','Escreva a resposta ideal e aprove o exemplo.'],[Check,'04','Revise','Teste novamente e só então use no atendimento.']].map(([Icon,num,title,copy])=>{const I=Icon as typeof BookOpen;return <article key={String(num)}><span className="step-icon"><I size={18}/></span><small>{String(num)}</small><h3>{String(title)}</h3><p>{String(copy)}</p></article>})}</div>
 <div className="school-grid"><section className="surface knowledge"><div className="section-heading"><div><h2><BookOpen size={20}/> Respostas aprovadas</h2><p>{config.knowledge.length} exemplos disponíveis para consulta</p></div><button className="btn outline" onClick={()=>{setEditing(null);setOpen(true)}}><Plus size={17}/>Adicionar</button></div><div className="knowledge-list">{config.knowledge.map(k=><article key={k.id}><div className="question-line"><span><MessageSquareText size={16}/>{k.question}</span><button className="icon-btn" aria-label={'Editar '+k.question} onClick={()=>{setEditing(k);setOpen(true)}}><Pencil size={16}/></button></div><p>{k.answer}</p><span className="micro-label"><Check size={13}/>Aprovado pela empresa</span></article>)}</div><div className="inline-tip"><ShieldCheck size={19}/><p>Cadastre respostas sem dados pessoais, promessas não autorizadas ou condições que mudam a cada orçamento.</p></div></section>
 <section className="surface playground"><div className="section-heading"><div><h2><FlaskConical size={20}/> Laboratório da IA</h2><p>Teste antes de colocar uma orientação em uso.</p></div><span className="pill neutral">Simulação</span></div><form onSubmit={e=>{e.preventDefault();const r=replyTo(question,config);setResult(r);setTestedQuestion(question);setCorrection(r.text);setApproved(false)}}><label className="field">O que o cliente perguntou?<textarea required value={question} onChange={e=>setQuestion(e.target.value)} rows={3}/></label><div className="suggested-questions">{['Vocês fazem instalação?','Vocês fazem panfletos?','Tem desconto?'].map(q=><button key={q} type="button" onClick={()=>setQuestion(q)}>{q}</button>)}</div><button className="btn primary" type="submit"><Sparkles size={17}/>Testar resposta</button></form>{result?<div className="test-result"><div className="result-top"><span className="mini-ai"><Sparkles size={15}/></span><b>Resposta demonstrativa</b></div><p>{result.text}</p><div className="source"><BookOpen size={14}/>{result.source}</div>{result.handoff&&<div className="inline-tip amber"><ShieldCheck size={18}/><span>Encaminharia para o vendedor: {result.handoff}</span></div>}<details className="correction"><summary><Pencil size={15}/>Ensinar uma resposta melhor</summary><label className="field">Resposta que a empresa aprova<textarea value={correction} onChange={e=>setCorrection(e.target.value)} rows={5}/></label><p className="muted">Salva um exemplo para esta pergunta exata. Regras de recusa e passagem ao humano têm prioridade.</p><button className="btn primary full" disabled={!correction.trim()||approved} onClick={()=>{const existing=config.knowledge.find(k=>k.question.toLowerCase()===testedQuestion.toLowerCase());saveExample(testedQuestion,correction,existing?.id);setApproved(true)}}><Check size={17}/>{approved?'Exemplo aprovado nesta sessão':'Aprovar e salvar exemplo'}</button></details></div>:<div className="lab-empty"><Sparkles size={28}/><h3>Um espaço seguro para aprender.</h3><p>Veja a resposta e a origem da informação, sem enviar nada ao cliente.</p></div>}<p className="demo-footnote">Este laboratório usa regras e exemplos, não um modelo de IA real. Perguntas novas podem ser encaminhadas ao vendedor. As alterações são reiniciadas ao recarregar.</p></section></div>
 <details className="education"><summary><Lightbulb size={19}/> Como melhorar minha IA ao longo do tempo?</summary><div className="education-grid"><article><h3>Uma fonte confiável</h3><p>Mantenha catálogo, condições e dúvidas frequentes atualizados. A IA conectada deve consultar essa base, não inventar informações ausentes.</p></article><article><h3>Revisão humana</h3><p>Separe respostas boas e ruins. Corrija exemplos com a equipe antes de aprová-los. Não deixe a IA aprender sozinha com tudo que um cliente escreve.</p></article><article><h3>Teste o que importa</h3><p>Repita perguntas sobre preço, prazo e serviços não oferecidos. Na versão real, compare acertos, encaminhamentos e reclamações antes de liberar uma nova orientação.</p></article></div><p>Isso é orientar a IA com contexto e exemplos; não é retreinar automaticamente o modelo. Uma IA integrada e memória permanente serão etapas futuras.</p></details>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="retoma-dialog"><DialogTitle>{editing?'Editar conhecimento':'Adicionar conhecimento'}</DialogTitle><DialogDescription>Uma pergunta frequente e a resposta aprovada pela empresa.</DialogDescription><form key={editing?.id||'new'} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);saveExample(String(f.get('question')),String(f.get('answer')),editing?.id);setOpen(false)}}><label className="field">Pergunta do cliente<input name="question" required defaultValue={editing?.question}/></label><label className="field">Resposta aprovada<textarea name="answer" required rows={5} defaultValue={editing?.answer}/></label><button className="btn primary full" type="submit"><Check size={17}/>Salvar conhecimento aprovado</button></form></DialogContent></Dialog>
 </div>
}

export function SettingsPage({config,onSave,onSchool}:{config:Config;onSave:(config:Config)=>void;onSchool:()=>void}){
 const [draft,setDraft]=useState<Config>(config),[section,setSection]=useState('business');
 const patch=(p:Partial<Config>)=>setDraft(d=>({...d,...p}));
 return <div className="content-page"><div className="page-title"><div><div className="eyebrow">SEU NEGÓCIO, SUAS REGRAS</div><h1>Configure o jeito de atender.</h1><p>Acompanhamento com autonomia definida e limites claros.</p></div><span className="version-tag">Orientações v{config.version}</span></div>
 <form onSubmit={e=>{e.preventDefault();if(draft.days.some((d,i)=>!Number.isInteger(d)||d<1||d>90||(i>0&&d<=draft.days[i-1]))){toast.add({title:'Revise os intervalos',description:'Use dias inteiros crescentes, entre 1 e 90.',type:'warning'});setSection('followups');return;}onSave({...draft,knowledge:config.knowledge,version:config.version+1});toast.add({title:'Orientações salvas nesta sessão',description:'Catálogo, horários, tom e regras selecionadas já podem ser testados.',type:'success'});}}>
 <Tabs value={section} onValueChange={v=>setSection(String(v))} className="settings-tabs"><TabsList className="section-tabs"><TabsTrigger value="business"><Building2 size={17}/>Empresa e serviços</TabsTrigger><TabsTrigger value="behavior"><SlidersHorizontal size={17}/>Comportamento</TabsTrigger><TabsTrigger value="followups"><Clock3 size={17}/>Retomadas</TabsTrigger></TabsList>
 <TabsContent value="business"><div className="settings-layout"><section className="surface settings-section"><div className="section-heading"><div><h2>Quem é a sua empresa?</h2><p>Informações que dão contexto ao atendimento.</p></div><Building2 size={24}/></div><div className="two-fields"><label className="field">Nome da empresa<input value={draft.company} required onChange={e=>patch({company:e.target.value})}/></label><label className="field">Nome do assistente<input value={draft.assistant} required onChange={e=>patch({assistant:e.target.value})}/></label></div><label className="field">Região de atendimento<input value={draft.region} required onChange={e=>patch({region:e.target.value})}/></label><label className="field">Horário de atendimento<input value={draft.hours} required onChange={e=>patch({hours:e.target.value})}/></label><p className="muted">Na simulação, o horário é uma informação de consulta; não há envios agendados em segundo plano.</p></section><section className="surface settings-section"><div className="section-heading"><div><h2>O que a empresa faz — e não faz</h2><p>Um escopo claro evita promessas erradas.</p></div><BookOpen size={24}/></div><label className="field">Produtos e serviços oferecidos<textarea required rows={4} value={draft.offer} onChange={e=>patch({offer:e.target.value})}/><small>Um serviço por linha. Ex.: fachadas em ACM; letras-caixa em LED.</small></label><label className="field">Serviços que não oferece<textarea rows={3} value={draft.excluded} onChange={e=>patch({excluded:e.target.value})}/></label><div className="inline-tip"><ShieldCheck size={19}/><span>A IA deve se limitar ao catálogo e pedir ajuda quando o serviço não estiver claro.</span></div></section></div></TabsContent>
 <TabsContent value="behavior"><div className="settings-layout"><section className="surface settings-section"><div className="section-heading"><div><h2>Personalidade e objetivo</h2><p>Atendimento natural, sem perder a responsabilidade.</p></div><MessageSquareText size={24}/></div><label className="field">Tom da conversa<NativeSelect value={draft.tone} onChange={e=>patch({tone:e.target.value})}><NativeSelectOption>Cordial e consultivo</NativeSelectOption><NativeSelectOption>Direto e objetivo</NativeSelectOption></NativeSelect></label><label className="field">Objetivo do assistente<textarea value={draft.objective} rows={4} onChange={e=>patch({objective:e.target.value})}/></label><label className="field">Limites e condições comerciais<textarea value={draft.limits} rows={4} onChange={e=>patch({limits:e.target.value})}/></label></section><section className="surface settings-section"><div className="section-heading"><div><h2>Quando chamar o vendedor</h2><p>Transferir com contexto, sem deixar o cliente esperando no escuro.</p></div><ShieldCheck size={24}/></div><div className="toggle-row"><div><b>Preço ou desconto</b><p>Pausar a IA e avisar o vendedor ao detectar uma negociação.</p></div><Switch checked={draft.priceHandoff} onCheckedChange={checked=>patch({priceHandoff:checked})} aria-label="Chamar vendedor para negociação de preço"/></div><label className="field">Outras situações para encaminhar<textarea rows={4} value={draft.handoff} onChange={e=>patch({handoff:e.target.value})}/></label><div className="fixed-rule"><Check size={17}/><span>Pedido para falar com uma pessoa: sempre encaminhar.</span></div><div className="fixed-rule"><Check size={17}/><span>Recusa de contato: sempre encerrar.</span></div><div className="fixed-rule"><Check size={17}/><span>Informação desconhecida: nunca inventar.</span></div><p className="demo-footnote">Os textos livres documentam as orientações da futura IA. Nesta simulação, funcionam apenas as regras identificadas, o tom e as respostas aprovadas; não há interpretação livre das instruções.</p></section></div></TabsContent>
 <TabsContent value="followups"><div className="settings-layout"><section className="surface settings-section"><div className="section-heading"><div><h2>Uma sequência, sem insistência</h2><p>Retomadas apenas em conversas autorizadas e paradas.</p></div><Clock3 size={24}/></div><div className="toggle-row"><div><b>Permitir retomadas</b><p>O vendedor ainda precisa ativar a IA em cada conversa.</p></div><Switch checked={draft.followups} onCheckedChange={checked=>patch({followups:checked})} aria-label="Permitir retomadas"/></div><div className="interval-grid">{draft.days.map((day,i)=><label className="field" key={i}><span className="number-disc">{i+1}</span>{i+1}ª tentativa<input type="number" min={1} max={90} required value={day} onChange={e=>patch({days:draft.days.map((d,j)=>i===j?Number(e.target.value):d)})}/><small>dias após o orçamento</small></label>)}</div><div className="inline-tip"><Clock3 size={20}/><span>Máximo de {draft.days.length} tentativas. No protótipo, use “Simular próxima retomada” para avançar o tempo.</span></div></section><section className="surface settings-section"><h2>Interrupções automáticas</h2><div className="rule-list">{['Cliente respondeu: interromper a sequência e continuar a conversa.','Cliente chamou o vendedor: pausar a IA e notificar.','Conversa vendida ou encerrada: parar o acompanhamento.','Cliente recusou contato: bloquear novas retomadas.','Limite de tentativas atingido: não insistir.'].map(r=><div key={r}><ShieldCheck size={18}/><p>{r}</p></div>)}</div></section></div></TabsContent>
 </Tabs><div className="settings-save"><span><ShieldCheck size={17}/>Use dados fictícios. Mudanças duram até recarregar.</span><button className="btn primary" type="submit"><Save size={17}/>Salvar orientações</button></div></form><button className="school-link" onClick={onSchool}><span><FlaskConical size={21}/><b>Quer saber como a IA responderia?</b></span><span>Ir para o laboratório <ArrowRight size={18}/></span></button></div>
}
