'use client';
import {useState} from 'react';
import {Sparkles,ShieldCheck,MessageSquareText,Headphones,Pause,Check,ArrowRight,Settings2,Search,BookOpen,Plug,Save} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Switch} from '@/components/ui/switch';
import {Checkbox} from '@/components/ui/checkbox';
import {business,catalogue,availability,productStates,serviceLabels,type Business,type Product} from './business-model';
import type {Config} from './recovery-model';
const zones=['America/Bahia','America/Sao_Paulo','America/Manaus','America/Cuiaba','America/Recife','America/Fortaleza','America/Belem','America/Rio_Branco'];
function SelectField({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(v:string)=>void}){return <label className="field">{label}<NativeSelect value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><NativeSelectOption key={o} value={o}>{o}</NativeSelectOption>)}</NativeSelect></label>}
function Checks({label,options,value,onChange}:{label:string;options:readonly string[];value:string[];onChange:(v:string[])=>void}){return <fieldset className="guided-checks"><legend>{label}</legend>{options.map(o=><label key={o}><Checkbox checked={value.includes(o)} onCheckedChange={v=>onChange(v?[...value,o]:value.filter(x=>x!==o))}/>{o}</label>)}</fieldset>}
const mandatory=['Não inventar informações.','Não prometer condições sem confirmação.','Respeitar pedidos de interrupção de contato.','Encaminhar pedidos de atendimento humano.','Pausar a IA quando o vendedor assumir.'];
export function School({config,onSave,onConfigure}:{config:Config;onSave:(c:Config)=>void;onConfigure:()=>void}){
 const [tab,setTab]=useState('how'),[draft,setDraft]=useState(config);
 const b=business(draft),patch=(p:Partial<Business>)=>setDraft(d=>({...d,business:{...business(d),...p}}));
 return <div className="content-page"><div className="page-title"><div><div className="eyebrow">ASSISTENTE RETOMA</div><h1>Você conhece a empresa. Nós cuidamos do método.</h1><p>Configure fatos e preferências, sem escrever prompts ou treinar a IA.</p></div><span className="pill green"><Sparkles size={15}/>Gemini real</span></div>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="section-tabs"><TabsTrigger value="how">Como funciona</TabsTrigger><TabsTrigger value="rules">Regras de atendimento</TabsTrigger></TabsList>
 <TabsContent value="how"><div className="integration-notice"><Plug size={22}/><div><b>WhatsApp ainda não está conectado</b><p>O Atendimento é um ambiente de teste com dados fictícios. A IA gera respostas reais, mas não lê nem envia mensagens pelo WhatsApp. Não há extensão instalada nem agendamento em segundo plano.</p></div></div>
 <div className="tutorial-flow">{[['1','Selecione a conversa','Abra um acompanhamento existente ou adicione contato e assunto. Orçamento e valor são opcionais.'],['2','Ative o acompanhamento','Revise contexto e autorização. Só a conversa selecionada será habilitada.'],['3','Retome o contato','Use “Simular próxima retomada”. Os intervalos são preferências salvas, não envios agendados.'],['4','Trate a resposta','Digite uma mensagem fictícia. A IA usa os fatos salvos e o histórico; a sequência de silêncio é suspensa.'],['5','Assuma quando necessário','O pedido de ajuda aparece no Retoma, com motivo e resumo. Não há notificação externa. Assumir pausa a IA.'],['6','Pause ou encerre','Pausar retomadas não desliga respostas. Pausar IA devolve o atendimento ao vendedor. Vendido, encerrado ou recusa bloqueiam retomadas.']].map(([n,t,d])=><article key={n}><span className="number-disc">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div>
 <section className="surface settings-section"><h2>O que orienta as respostas</h2><div className="education-grid"><article><BookOpen/><h3>Método do Retoma</h3><p>Regras centrais e conteúdo aprovado pelo SaaS. A base técnica especializada está em preparação; conteúdo sem revisão não é usado.</p></article><article><Settings2/><h3>Fatos da sua empresa</h3><p>Produtos oferecidos, serviços e condições confirmadas. Ativar um produto não inicia contatos.</p></article><article><MessageSquareText/><h3>Contexto da conversa</h3><p>Histórico e informações específicas. Um valor antigo não comprova preço vigente.</p></article></div><button className="btn outline" onClick={onConfigure}>Configurar minha empresa <ArrowRight size={16}/></button></section></TabsContent>
 <TabsContent value="rules"><form onSubmit={e=>{e.preventDefault();onSave(draft)}}><div className="settings-layout"><section className="surface settings-section"><h2>Retomadas automáticas</h2><p>Preferências preparadas para a conexão futura. Atualmente o tempo é avançado manualmente nos testes.</p><div className="toggle-row"><div><b>Pausa geral da automação</b><p>Bloqueia retomadas e respostas automáticas em todas as conversas. O vendedor continua podendo atender.</p></div><Switch checked={b.paused} onCheckedChange={v=>patch({paused:v})} aria-label="Pausa geral"/></div>
 <div className="two-fields"><label className="field">Início<input type="time" required value={b.autoStart} onChange={e=>patch({autoStart:e.target.value})}/></label><label className="field">Fim<input type="time" required value={b.autoEnd} onChange={e=>patch({autoEnd:e.target.value})}/></label></div><p>Fuso da empresa: {b.timezone}. Altere em Dados da empresa.</p>
 <Checks label="Dias de retomada" options={['Seg','Ter','Qua','Qui','Sex','Sáb','Dom']} value={b.autoDays} onChange={autoDays=>patch({autoDays})}/>
 <label className="field">Limite de tentativas<NativeSelect value={String(draft.days.length)} onChange={e=>setDraft(d=>({...d,days:Array.from({length:Number(e.target.value)},(_,i)=>d.days[i]??(d.days.at(-1)||0)+(i-d.days.length+1)*3)}))}>{[1,2,3,4,5].map(n=><NativeSelectOption key={n} value={String(n)}>{n}</NativeSelectOption>)}</NativeSelect></label>
 <div className="interval-grid">{draft.days.map((d,i)=><label className="field" key={i}>{i+1}ª tentativa<input type="number" min={i?draft.days[i-1]+1:1} max={90} required value={d} onChange={e=>setDraft(c=>({...c,days:c.days.map((v,j)=>j===i?Number(e.target.value):v)}))}/><small>Dias após início do acompanhamento</small></label>)}</div>
 </section><section className="surface settings-section"><h2>Atendimento e encaminhamentos</h2><SelectField label="Tom da conversa" value={draft.tone} options={['Cordial e consultivo','Direto e objetivo']} onChange={tone=>setDraft(d=>({...d,tone}))}/>
 <div className="inline-tip"><Headphones size={20}/><span>Responsável: {b.humanContact||'Não informado'}. <button type="button" className="text-link" onClick={onConfigure}>Configurar nos dados da empresa</button></span></div>
 <Checks label="Situações adicionais para chamar o vendedor" options={['Alteração de projeto','Prazo urgente','Negociação de preço','Visita técnica','Pedido fora da região']} value={b.extraHandoff} onChange={extraHandoff=>patch({extraHandoff})}/>
 <h3>Regras obrigatórias</h3>{mandatory.map(r=><div className="fixed-rule" key={r}><ShieldCheck size={17}/><span>{r}</span></div>)}<p>O horário humano é informativo e não garante resposta imediata. As preferências de retomada não criam agenda real nesta etapa.</p></section></div><div className="settings-save"><span>Regras centrais não podem ser desativadas.</span><button className="btn primary"><Save size={16}/>Salvar preferências</button></div></form></TabsContent></Tabs></div>
}
export function SettingsPage({config,onSave,onSchool}:{config:Config;onSave:(c:Config)=>void;onSchool:()=>void}){
 const [tab,setTab]=useState('business'),[draft,setDraft]=useState(config);const b=business(draft);
 const patch=(p:Partial<Business>)=>setDraft(d=>({...d,business:{...business(d),...p}}));
 return <div className="content-page"><div className="page-title"><div><div className="eyebrow">CONFIGURAÇÕES</div><h1>Fatos que tornam o atendimento confiável.</h1><p>Preencha somente o que foi confirmado pela empresa.</p></div></div>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="section-tabs"><TabsTrigger value="business">Dados da empresa</TabsTrigger><TabsTrigger value="products">Produtos e serviços</TabsTrigger><TabsTrigger value="integrations">Integrações</TabsTrigger></TabsList>
 <TabsContent value="business"><form onSubmit={e=>{e.preventDefault();onSave({...draft,business:{...b,products:business(config).products}})}}><div className="settings-layout"><section className="surface settings-section"><h2>Identidade e atendimento humano</h2><div className="two-fields"><label className="field">Nome comercial<input value={draft.company} required maxLength={200} onChange={e=>setDraft(d=>({...d,company:e.target.value}))}/></label><label className="field">Nome da assistente<input value={draft.assistant} required maxLength={80} onChange={e=>setDraft(d=>({...d,assistant:e.target.value}))}/></label></div><label className="field">Região atendida<input value={draft.region} maxLength={300} placeholder="Não informado" onChange={e=>setDraft(d=>({...d,region:e.target.value}))}/></label><SelectField label="Dias de atendimento humano" value={b.humanDays} options={['Não informado','Segunda a sexta','Segunda a sábado','Todos os dias','Somente com agendamento']} onChange={humanDays=>patch({humanDays})}/>
 <div className="two-fields"><label className="field">Abertura<input type="time" value={b.humanStart} onChange={e=>patch({humanStart:e.target.value})}/></label><label className="field">Encerramento<input type="time" value={b.humanEnd} onChange={e=>patch({humanEnd:e.target.value})}/></label></div><SelectField label="Fuso horário" value={b.timezone} options={zones} onChange={timezone=>patch({timezone})}/>
 <label className="field">Responsável ou canal humano<input value={b.humanContact} maxLength={200} placeholder="Ex.: Equipe comercial · ramal 2" onChange={e=>patch({humanContact:e.target.value})}/></label><p>Referência interna. Não dispara notificações externas.</p></section>
 <section className="surface settings-section"><h2>Serviços gerais</h2>{Object.entries(serviceLabels).map(([key,label])=><SelectField key={key} label={label} value={b[key as keyof Business] as string} options={availability} onChange={v=>patch({[key]:v})}/>)}<div className="inline-tip"><ShieldCheck/><span>Disponível não significa incluso no orçamento. Preço, prazo, garantia e parcelamento precisam de confirmação específica.</span></div><Checks label="Formas de pagamento confirmadas (opcional)" options={['Pix','Dinheiro','Cartão de crédito','Cartão de débito','Boleto','Transferência']} value={b.payments} onChange={payments=>patch({payments})}/></section></div><div className="settings-save"><span>Campos vazios permanecem não informados.</span><button className="btn primary"><Save size={16}/>Salvar dados da empresa</button></div></form></TabsContent>
 <TabsContent value="products"><ProductCatalogue config={config} onSave={onSave}/></TabsContent>
 <TabsContent value="integrations"><div className="settings-layout"><section className="surface settings-section"><span className="pill green">Integração real</span><h2>Gemini 3.1 Flash-Lite</h2><p>Chamadas no servidor, com chave protegida. Recebe fatos salvos e histórico de teste; apenas conteúdo central aprovado é recuperado.</p><p>Use somente dados fictícios. A faixa gratuita tem cotas e pode usar conteúdo para melhoria dos produtos do Google.</p></section><section className="surface settings-section"><span className="pill amber">Não conectado</span><h2>WhatsApp</h2><p>Sem leitura, envio, templates ou agenda automática. Nenhuma mensagem gerada é marcada como enviada ao WhatsApp.</p><p>A integração oficial, as credenciais e as regras de janela/templates serão necessárias antes de ativar clientes reais.</p></section><section className="surface settings-section"><span className="pill green">Persistência no servidor</span><h2>Empresa e acompanhamentos</h2><p>Dados de teste isolados pela conta autenticada. Uma empresa por conta nesta etapa; equipes com múltiplos usuários ainda precisam de gestão de membros.</p></section></div><button className="btn outline" onClick={onSchool}>Como funciona o assistente <ArrowRight size={16}/></button></TabsContent></Tabs></div>
}
function ProductCatalogue({config,onSave}:{config:Config;onSave:(c:Config)=>void}){
 const b=business(config),[query,setQuery]=useState(''),[category,setCategory]=useState('Todas'),[state,setState]=useState('Todos'),[editing,setEditing]=useState<Product|null>(null);
 const filtered=catalogue.filter(c=>c[1].toLowerCase().includes(query.toLowerCase())&&(category==='Todas'||c[2]===category)&&(state==='Todos'||b.products.find(p=>p.id===c[0])?.state===state));
 const update=(p:Partial<Product>)=>setEditing(e=>e?{...e,...p}:e);
 return <><div className="catalogue-filters"><label className="search-box"><Search size={18}/><input aria-label="Buscar produto" placeholder="Buscar produto…" value={query} onChange={e=>setQuery(e.target.value)}/></label><SelectField label="Categoria" value={category} options={['Todas',...new Set(catalogue.map(c=>c[2]))]} onChange={setCategory}/><SelectField label="Estado" value={state} options={['Todos',...productStates]} onChange={setState}/></div>
 <p className="inline-tip">A lista mostra possibilidades do setor, não serviços automaticamente oferecidos. Selecionar um produto nunca inicia contatos.</p>
 <div className="catalogue-grid">{filtered.map(([id,name,cat,description])=>{const p=b.products.find(p=>p.id===id)!;return <article className="surface product-card" key={id}><small>{cat}</small><h3>{name}</h3><p>{description}</p><span className={'pill '+(p.state==='Oferecemos'?'green':p.state==='Não oferecemos'?'neutral':'amber')}>{p.state}</span><p><b>Confirmado:</b> {p.state==='Oferecemos'?[...p.materials,...p.finishes,...p.applications].join(', ')||'Oferta confirmada; características não informadas.':p.state==='Não oferecemos'?'Não oferecido pela empresa.':'Nenhuma oferta confirmada.'}</p><p><b>Pendências:</b> {p.state==='Oferecemos'?'Confirmar condições, inclusão, prazo e características não preenchidas.':p.state==='Não configurado'?'Confirmar se a empresa oferece.':'Sem configuração de oferta.'}</p><button className="btn outline full" onClick={()=>setEditing(structuredClone(p))}>Configurar <Settings2 size={16}/></button></article>})}</div>{!filtered.length&&<p>Nenhum produto encontrado.</p>}
 <Sheet open={!!editing} onOpenChange={v=>{if(!v)setEditing(null)}}><SheetContent className="product-sheet">{editing&&<><SheetTitle>{catalogue.find(c=>c[0]===editing.id)?.[1]}</SheetTitle><SheetDescription>Registre apenas opções confirmadas. Serviços gerais podem ser substituídos explicitamente neste produto.</SheetDescription><form onSubmit={e=>{e.preventDefault();onSave({...config,business:{...b,products:b.products.map(p=>p.id===editing.id?editing:p)}});setEditing(null)}}><SelectField label="Estado do produto" value={editing.state} options={productStates} onChange={state=>update({state:state as Product['state']})}/>
 {editing.state==='Oferecemos'&&<><details open><summary>Características confirmadas</summary><Checks label="Materiais" options={editing.id==='acm'?['ACM']:editing.id==='banner'?['Lona','Tecido']:['vitrine','parede','veiculo','piso'].includes(editing.id)?['Vinil adesivo']:[]} value={editing.materials} onChange={materials=>update({materials})}/><Checks label="Acabamentos" options={editing.id==='acm'?['Pintura','Recorte']:editing.id==='banner'?['Ilhós','Bastão','Bainha']:['vitrine','parede','veiculo','piso'].includes(editing.id)?['Laminação','Recorte']:[]} value={editing.finishes} onChange={finishes=>update({finishes})}/><Checks label="Aplicações atendidas" options={['Ambiente interno','Ambiente externo']} value={editing.applications} onChange={applications=>update({applications})}/><p>Opções são possibilidades para confirmação, não garantias de desempenho.</p></details>
 <details open><summary>Serviços deste produto</summary>{Object.entries(serviceLabels).map(([key,label])=><div key={key}><SelectField label={label} value={editing[key as keyof Product] as string} options={['Padrão da empresa',...availability]} onChange={v=>update({[key]:v})}/><small>{editing[key as keyof Product]==='Padrão da empresa'?'Herdado: '+b[key as keyof Business]:'Exceção explícita para este produto.'}</small></div>)}</details><label className="field">Restrições confirmadas<textarea maxLength={1000} rows={3} value={editing.restrictions} onChange={e=>update({restrictions:e.target.value})}/></label><p>Instalação disponível não significa instalação inclusa. Nunca presumir preço, prazo, parcelamento ou garantia.</p></>}
 <button className="btn primary full"><Check size={16}/>Salvar configuração</button></form></>}</SheetContent></Sheet></>
}
