'use client';
import {useEffect,useState} from 'react';
import {MessageCircle,BarChart3,BookOpen,Settings2,Bell,Search,Sparkles,UserRound,Send,Pause,Play,ShieldCheck,Headphones,Wifi,WifiOff} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Toaster,toast} from '@/components/ui/toast';
import {useWorkspace} from './use-workspace';
import {School,SettingsPage} from './ai-school';
import {MessageBody} from './message-body';
import {statuses,terminal,type Lead,type Status} from './recovery-model';
import {business} from './business-model';
import {sendOfficialMessage} from './whatsapp-client';

const initials=(name:string)=>name.split(/\s+/).filter(Boolean).map(part=>part[0]).slice(0,2).join('').toUpperCase();
export default function OfficialDashboard(){
 const workspace=useWorkspace(),[view,setView]=useState('atendimento'),[selected,setSelected]=useState(0),[search,setSearch]=useState(''),[draft,setDraft]=useState(''),[sending,setSending]=useState(false);
 const leads=workspace.leads.filter(lead=>lead.externalId?.startsWith('whatsapp:'));
 const lead=leads.find(item=>item.id===selected)||leads[0];
 useEffect(()=>{if(lead&&!selected)setSelected(lead.id)},[lead?.id,selected]);
 const update=(id:number,change:(lead:Lead)=>Lead)=>workspace.setLeads(items=>items.map(item=>item.id===id?change(item):item));
 const notify=(title:string,description?:string)=>toast.add({title,description,type:'success'});
 async function send(){if(!lead||!draft.trim()||sending)return;setSending(true);try{await workspace.flush();await sendOfficialMessage(lead.id,draft.trim());setDraft('');await workspace.reload();notify('Mensagem enviada','A mensagem foi entregue pela API oficial do WhatsApp.')}catch(error){toast.add({title:'Não foi possível enviar',description:error instanceof Error?error.message:'Tente novamente.',type:'warning'})}finally{setSending(false)}}
 if(!workspace.ready)return <main className="official-loading"><img src="/retoma-icon.png" alt=""/><b>Carregando o Retoma…</b><span>{workspace.error}</span></main>;
 const alerts=leads.filter(item=>item.needsHuman).length,active=leads.filter(item=>item.ai).length;
 return <Toaster><div className="official-shell"><header className="official-header"><button className="official-brand" onClick={()=>setView('atendimento')}><img src="/retoma-icon.png" alt=""/><b>retoma</b></button><div className="official-company"><span>{initials(workspace.config.company)}</span><div><b>{workspace.config.company}</b><small>Atendimento oficial</small></div></div><div className="official-live"><Wifi size={16}/>API oficial conectada</div><button className="official-bell" onClick={()=>setView('atendimento')} aria-label={`${alerts} alertas`}><Bell size={20}/>{alerts>0&&<b>{alerts}</b>}</button></header>
 <Tabs value={view} onValueChange={value=>setView(String(value))}><nav className="official-nav"><TabsList><TabsTrigger value="atendimento"><MessageCircle size={17}/>Atendimento</TabsTrigger><TabsTrigger value="resultados"><BarChart3 size={17}/>Resultados</TabsTrigger><TabsTrigger value="assistente"><BookOpen size={17}/>Assistente</TabsTrigger><TabsTrigger value="configuracoes"><Settings2 size={17}/>Configurações</TabsTrigger></TabsList><span>{workspace.saving?'Salvando…':workspace.error||'Dados sincronizados'}</span></nav>
 <TabsContent value="atendimento"><main className="official-main"><section className="official-title"><div><small>ATENDIMENTO COM IA</small><h1>Conversas do WhatsApp</h1><p>As mensagens chegam pelo webhook oficial. Nenhuma extensão é necessária.</p></div><div className="official-metrics"><span><b>{active}</b> com IA</span><span><b>{alerts}</b> precisam de você</span></div></section>
 {!lead?<section className="official-empty"><WifiOff size={34}/><h2>Aguardando a primeira conversa</h2><p>Quando um cliente enviar uma mensagem para o número conectado à API oficial, ela aparecerá aqui automaticamente.</p><button onClick={()=>setView('configuracoes')}>Ver conexão do WhatsApp</button></section>:
 <section className="official-inbox"><aside><label><Search size={17}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar cliente"/></label><div>{leads.filter(item=>(item.name+' '+item.service).toLowerCase().includes(search.toLowerCase())).map(item=><button key={item.id} className={item.id===lead.id?'selected':''} onClick={()=>{setSelected(item.id);setDraft('')}}><span className="official-avatar">{initials(item.name)}</span><div><b>{item.name}</b><p>{item.messages.at(-1)?.text||'Sem mensagens'}</p><small>{item.needsHuman?'Precisa de você':item.ai?'IA atendendo':'Atendimento humano'}</small></div>{item.needsHuman&&<i/>}</button>)}</div></aside>
 <article className="official-chat"><header><span className="official-avatar">{initials(lead.name)}</span><div><h2>{lead.name}</h2><p>{lead.service}</p></div><span className={lead.ai?'ai':'human'}>{lead.ai?<Sparkles size={15}/>:<UserRound size={15}/>} {lead.ai?'IA ativa':'Vendedor'}</span></header>{lead.needsHuman&&<div className="official-alert"><Headphones size={19}/><div><b>O vendedor foi chamado</b><p>{lead.reason||'Esta conversa precisa de atendimento humano.'}</p></div></div>}
 <div className="official-messages">{lead.messages.map((message,index)=><div key={message.id||index} className={'official-message '+message.role}>{message.role==='ia'&&<small><Sparkles size={13}/>{workspace.config.assistant} · IA</small>}{message.role==='ia'?<MessageBody text={message.text}/>:<p>{message.text}</p>}<time>{message.role==='cliente'?'Cliente':message.role==='ia'?'Assistente virtual':'Vendedor'}</time></div>)}</div>
 <footer>{lead.ai?<div className="official-ai-control"><Sparkles size={18}/><span>{lead.needsHuman?'A IA segue respondendo até você assumir.':'A IA está cuidando desta conversa.'}</span><button onClick={()=>{update(lead.id,item=>({...item,ai:false,needsHuman:false,due:'Atendimento manual',history:[...item.history,'Vendedor assumiu pelo painel.']}));notify('Atendimento assumido')}}><Pause size={15}/>Assumir conversa</button></div>:<form onSubmit={event=>{event.preventDefault();void send()}}><input value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Responder pelo WhatsApp oficial…" disabled={sending||terminal(lead)}/><button disabled={sending||!draft.trim()}><Send size={18}/></button></form>}</footer></article>
 <aside className="official-side"><small>CONTROLE DA CONVERSA</small><h2>{lead.ai?'Assistente acompanhando':'Atendimento humano'}</h2><p>{lead.aiSummary||'O resumo será atualizado conforme a conversa avançar.'}</p><label>Status<NativeSelect value={lead.status} onChange={event=>update(lead.id,item=>({...item,status:event.target.value as Status}))}>{statuses.map(status=><NativeSelectOption key={status}>{status}</NativeSelectOption>)}</NativeSelect></label>{!lead.ai&&!terminal(lead)&&<button onClick={()=>{update(lead.id,item=>({...item,ai:true,due:'Aguardando cliente',history:[...item.history,'IA reativada pelo vendedor.']}));notify('IA reativada')}}><Play size={16}/>Devolver para a IA</button>}<div><ShieldCheck size={18}/><span>A IA usa apenas os produtos, serviços e regras aprovados nas configurações.</span></div></aside></section>}
 </main></TabsContent>
 <TabsContent value="resultados"><main className="official-main"><section className="official-title"><div><small>RESULTADOS REAIS</small><h1>Atendimento no WhatsApp</h1><p>Indicadores calculados somente com conversas recebidas pela API oficial.</p></div></section><div className="official-result-grid"><article><span>Conversas</span><b>{leads.length}</b></article><article><span>Atendidas pela IA</span><b>{leads.filter(item=>item.messages.some(message=>message.role==='ia')).length}</b></article><article><span>Chamados ao vendedor</span><b>{leads.filter(item=>item.needsHuman).length}</b></article><article><span>Vendidos</span><b>{leads.filter(item=>item.status==='Vendido').length}</b></article></div></main></TabsContent>
 <TabsContent value="assistente"><School config={workspace.config} onSave={workspace.setConfig} onConfigure={()=>setView('configuracoes')}/></TabsContent>
 <TabsContent value="configuracoes"><SettingsPage config={workspace.config} onSave={workspace.setConfig} onSchool={()=>setView('assistente')}/></TabsContent>
 </Tabs></div></Toaster>;
}
