'use client';
import { useState, useEffect } from 'react';
import { flushSync } from 'react-dom';
import { ArrowUpRight, RotateCcw, MessageCircle, LayoutDashboard, Settings, Search, Plus, Sparkles, Send, Check, Clock3, Pause, ChevronRight, ShieldCheck, FileText, TrendingUp, CircleDollarSign } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table';
type Lead = {id:number; name:string; company:string; service:string; value:number; status:string; next:string; paused:boolean; messages:{text:string;out:boolean}[]};
const seed:Lead[] = [
 {id:1,name:'Carlos Mendes',company:'Café do Centro',service:'Fachada em ACM • 4 × 1,2 m',value:2850,status:'Aguardando retorno',next:'Hoje',paused:false,messages:[{text:'Oi! Gostaria de um orçamento para a fachada do meu café. Posso mandar as medidas?',out:false},{text:'Claro, Carlos! Com as medidas que você enviou, preparei a proposta da fachada em ACM. A instalação está inclusa.',out:true},{text:'Orçamento #1042\nFachada em ACM • 4 × 1,2 m\nValor total: R$ 2.850,00',out:true},{text:'Obrigado! Vou olhar com minha sócia e te aviso.',out:false}]},
 {id:2,name:'Mariana Costa',company:'Studio MC',service:'Letreiro iluminado',value:1640,status:'Em conversa',next:'Responder',paused:false,messages:[{text:'Adorei o letreiro, mas o valor ficou acima do que eu esperava.',out:false}]},
 {id:3,name:'Rafael Lima',company:'RL Barbearia',service:'Adesivação de vitrine',value:890,status:'Aguardando retorno',next:'Hoje',paused:false,messages:[{text:'Recebi o orçamento. Vou avaliar com calma!',out:false}]},
 {id:4,name:'Beatriz Souza',company:'Flora Boutique',service:'Placa e sinalização interna',value:1250,status:'Recuperado',next:'Concluído',paused:false,messages:[{text:'Pode fechar! Vamos seguir com a proposta.',out:false}]},
 {id:5,name:'Pedro Alves',company:'Alves Auto',service:'Banner e comunicação de loja',value:720,status:'Aguardando retorno',next:'Amanhã',paused:false,messages:[{text:'Vou ver aqui e depois conversamos.',out:false}]}
];
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const initials=(n:string)=>n.split(' ').map(p=>p[0]).slice(0,2).join('');
export default function Home(){
 const [leads,setLeads]=useState(seed),[active,setActive]=useState(1),[tab,setTab]=useState('workspace'),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'),[draft,setDraft]=useState(''),[suggestion,setSuggestion]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(false),[company,setCompany]=useState('Forma Comunicação Visual'),[rules,setRules]=useState('Não oferecer descontos sem aprovação. Confirmar prazos com a equipe.'),[days,setDays]=useState([1,3,7]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'navigate_recovery_demo',description:'Navega entre as áreas do protótipo Retoma. Não envia mensagens nem altera orçamentos.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['workspace','pipeline','results','settings']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const view=(input as {view?:unknown})?.view;if(typeof view!=='string'||!['workspace','pipeline','results','settings'].includes(view))throw new Error('Área inválida');flushSync(()=>setTab(view));return {view,demo:true};}});
  return ()=>lifecycle.abort();
 },[]);
 const lead=leads.find(l=>l.id===active)!;
 const closed=lead.status==='Recuperado'||lead.status==='Encerrado';
 const notify=(s:string)=>setNotice(s);
 const update=(patch:Partial<Lead>)=>setLeads(ls=>ls.map(l=>l.id===active?{...l,...patch}:l));
 const choose=(l:Lead)=>{setActive(l.id);setSuggestion('');setDraft('');};
 const visible=leads.filter(l=>(l.name+' '+l.company+' '+l.service).toLowerCase().includes(query.toLowerCase())&&(filter==='Todos'||(filter==='Hoje'?l.next==='Hoje'&&!l.paused&&!['Recuperado','Encerrado'].includes(l.status):l.status===filter)));
 const pending=leads.filter(l=>!['Recuperado','Encerrado'].includes(l.status));
 const due=pending.filter(l=>l.next==='Hoje'&&!l.paused).length;
 const recovered=leads.filter(l=>l.status==='Recuperado');
 const generate=()=>{const first=lead.name.split(' ')[0];setSuggestion(lead.status==='Em conversa'?`Entendo, ${first}! O que mais pesou para você na proposta? Posso conversar com a equipe sobre uma alternativa que se ajuste ao que você precisa, sem abrir mão do resultado.`:`Oi, ${first}! Tudo bem? Conseguiu avaliar a proposta de ${lead.service.split(' • ')[0].toLowerCase()}? Se ficou alguma dúvida sobre o projeto, estou por aqui para ajudar.`);notify('Sugestão demonstrativa criada. Revise antes de usar.');};
 return <div className="app"><Tabs value={tab} onValueChange={v=>setTab(String(v))} className="app-tabs">
 <header className="topbar"><a href="#" className="brand" onClick={e=>{e.preventDefault();setTab('workspace')}}><span className="brand-mark"><RotateCcw size={23}/></span>retoma<span className="beta">BETA</span></a><TabsList className="nav-tabs"><TabsTrigger value="workspace"><MessageCircle/>Assistente</TabsTrigger><TabsTrigger value="pipeline"><LayoutDashboard/>Recuperações</TabsTrigger><TabsTrigger value="results"><TrendingUp/>Resultados</TabsTrigger><TabsTrigger value="settings"><Settings/>Configurações</TabsTrigger></TabsList><div className="account"><span className="avatar small">FC</span><span>Forma Visual<small>Espaço de demonstração</small></span></div></header>
 <div className="demo-strip"><span><span className="live-dot"/> Protótipo interativo <span className="strip-sep">/</span> Dados fictícios · IA simulada · nenhum envio real</span><span className="desktop-only">Alterações duram até recarregar</span></div>
 <TabsContent value="workspace" className="workspace-content"><section className="page-heading"><div><div className="eyebrow">SEU COPILOTO DE VENDAS</div><h1>Uma nova chance de fechar.</h1><p>Retome a conversa certa, no momento certo.</p></div><div className="today-box"><Clock3 size={19}/><span><b>{due} retomadas</b> para hoje</span><button className="text-button" onClick={()=>{setFilter('Hoje');setTab('pipeline')}}>Ver fila <ArrowUpRight size={17}/></button></div></section>
 <div className="workspace"><aside className="contacts"><div className="contacts-title"><h2>Conversas</h2><span className="count">{leads.length}</span></div><label className="search"><Search size={17}/><input aria-label="Buscar conversas" placeholder="Buscar cliente ou orçamento" value={query} onChange={e=>setQuery(e.target.value)} /></label><div className="contact-list">{leads.filter(l=>(l.name+' '+l.company).toLowerCase().includes(query.toLowerCase())).map(l=><button key={l.id} className={'contact '+(active===l.id?'selected':'')} onClick={()=>choose(l)}><span className={'avatar color-'+l.id}>{initials(l.name)}</span><span className="contact-copy"><b>{l.name}</b><span>{l.company}</span><small>{l.status==='Recuperado'?'✓ Venda recuperada':l.paused?'Acompanhamento pausado':l.next==='Hoje'?'Retomar hoje':'Próximo contato: '+l.next}</small></span>{l.next==='Hoje'&&!l.paused&&<span className="unread"/>}</button>)}</div><div className="contacts-foot"><ShieldCheck size={16}/> WhatsApp simulado</div></aside>
 <section className="chat"><header className="chat-header"><span className={'avatar color-'+lead.id}>{initials(lead.name)}</span><div><h2>{lead.name}</h2><p>{lead.company}</p></div><span className="chat-badge">DEMONSTRAÇÃO</span></header><div className="messages"><span className="date-chip">Orçamento enviado · 01 set.</span>{lead.messages.map((m,i)=><div key={i} className={'bubble '+(m.out?'out':'in')}>{m.text.includes('Orçamento #')&&<FileText size={24}/>}<p>{m.text}</p><small>{m.out?'Você':'Cliente'} · {i===lead.messages.length-1?'última mensagem':'10:'+String(20+i*3)} {m.out&&<Check size={14}/>}</small></div>)}{!closed&&<div className="conversation-hint"><Clock3 size={15}/>{lead.status==='Em conversa'?'Cliente respondeu. A sequência está interrompida.':'Uma boa conversa não precisa terminar aqui.'}</div>}</div><form className="composer" onSubmit={e=>{e.preventDefault();if(!draft.trim())return;update({messages:[...lead.messages,{text:draft.trim(),out:true}],next:lead.status==='Em conversa'?'Responder':'Amanhã'});setDraft('');notify('Mensagem adicionada somente à conversa simulada.');}}><input aria-label="Mensagem simulada" placeholder="Revise a sugestão ou escreva uma mensagem…" value={draft} onChange={e=>setDraft(e.target.value)}/><button className="send" type="submit" disabled={!draft.trim()} aria-label="Enviar na simulação"><Send size={19}/></button></form><div className="send-note">O envio acima acontece apenas nesta demonstração.</div></section>
 <aside className="assistant"><div className="assistant-heading"><span className="assistant-icon"><Sparkles size={21}/></span><div><h2>Assistente Retoma</h2><p>Você no controle. IA ao seu lado.</p></div><span className="live-dot"/></div><div className="assistant-body"><div className="section-label">ORÇAMENTO EM ACOMPANHAMENTO <FileText size={15}/></div><h3>{lead.service}</h3><div className="quote-value">{money(lead.value)}</div><span className={'status '+(lead.status==='Recuperado'?'green':'')}>{lead.paused?'Pausado':lead.status}</span><div className="divider"/>
 <div className="section-label">PRÓXIMO PASSO <Clock3 size={15}/></div><div className="next-step"><span className="step-number">1</span><div><b>{closed?'Acompanhamento concluído':lead.paused?'Acompanhamento pausado':lead.status==='Em conversa'?'Responder à objeção':'Retomar a conversa'}</b><p>{closed?'Nenhuma nova tentativa será sugerida.':lead.status==='Em conversa'?'Entenda o que impede o fechamento.':`Lembrete: ${lead.next.toLowerCase()} · envio manual`}</p></div></div>
 <div className="ai-card"><div className="ai-label"><Sparkles size={16}/> SUGESTÃO COM IA <span>SIMULADA</span></div>{suggestion?<textarea aria-label="Editar sugestão" value={suggestion} onChange={e=>setSuggestion(e.target.value)}/>:<p>Uma abordagem leve, com o contexto do orçamento e sem pressionar seu cliente.</p>}<button className="primary full" disabled={closed||lead.paused} onClick={generate}><Sparkles size={17}/>{suggestion?'Recriar sugestão':'Preparar mensagem'}</button>{suggestion&&<button className="secondary full" disabled={closed||lead.paused} onClick={()=>{setDraft(suggestion);notify('Texto colocado no campo da conversa para revisão.')}}>Usar na conversa <ChevronRight size={16}/></button>}<small><ShieldCheck size={13}/> Nenhuma mensagem é enviada pela IA.</small></div>
 <div className="actions-row"><button className="secondary" disabled={closed} onClick={()=>{update({next:'Amanhã'});notify('Próximo contato adiado para amanhã.')}}><Clock3 size={15}/>Adiar</button><button className="secondary" disabled={closed} onClick={()=>{update({paused:!lead.paused});notify(lead.paused?'Acompanhamento retomado.':'Acompanhamento pausado.')}}><Pause size={15}/>{lead.paused?'Retomar':'Pausar'}</button></div><button className="success-button full" disabled={closed} onClick={()=>{update({status:'Recuperado',next:'Concluído',paused:false});notify('Venda marcada como recuperada. Veja o painel de resultados.')}}><Check size={17}/>Marcar venda recuperada</button><button className="end-button" disabled={closed} onClick={()=>{update({status:'Encerrado',next:'Concluído'});notify('Recuperação encerrada. Não haverá novas tentativas.')}}>Encerrar sem venda</button><details className="demo-controls"><summary>Testar uma resposta do cliente</summary><button className="secondary full" disabled={closed} onClick={()=>{update({status:'Em conversa',next:'Responder',messages:[...lead.messages,{text:'Gostei da proposta, mas achei o preço um pouco alto. O que podemos fazer?',out:false}]});setSuggestion('');notify('Resposta simulada. Retomadas interrompidas para conversar.')}}>Simular objeção de preço</button></details></div></aside></div></TabsContent>
 <TabsContent value="pipeline" className="panel-page"><div className="page-heading"><div><div className="eyebrow">CADA ORÇAMENTO CONTA</div><h1>Recuperações</h1><p>As oportunidades que merecem uma segunda conversa.</p></div><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/>Acompanhar orçamento</button></div><div className="metrics"><article><span>Em acompanhamento</span><strong>{money(pending.reduce((s,l)=>s+l.value,0))}</strong><small>{pending.length} oportunidades abertas</small></article><article><span>Para retomar hoje</span><strong>{due.toString().padStart(2,'0')}</strong><small>Contatos aguardando sua ação</small></article><article className="metric-green"><span>Vendas recuperadas</span><strong>{money(recovered.reduce((s,l)=>s+l.value,0))}</strong><small>Confirmadas pelo vendedor · demonstração</small></article></div><div className="table-card"><div className="table-toolbar"><Tabs value={filter} onValueChange={v=>setFilter(String(v))}><TabsList>{['Todos','Hoje','Em conversa','Recuperado'].map(f=><TabsTrigger value={f} key={f}>{f}</TabsTrigger>)}</TabsList></Tabs><label className="search"><Search size={17}/><input aria-label="Buscar recuperações" placeholder="Buscar orçamento…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><Table><TableHeader><TableRow>{['Cliente / empresa','Orçamento','Valor','Situação','Próximo contato',''].map((h,i)=><TableHead key={i}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(l=><TableRow key={l.id}><TableCell><div className="table-person"><span className={'avatar small color-'+l.id}>{initials(l.name)}</span><div><b>{l.name}</b><small>{l.company}</small></div></div></TableCell><TableCell>{l.service}</TableCell><TableCell className="money">{money(l.value)}</TableCell><TableCell><span className={'status '+(l.status==='Recuperado'?'green':'')}>{l.paused?'Pausado':l.status}</span></TableCell><TableCell>{l.next}</TableCell><TableCell><button className="text-button" onClick={()=>{choose(l);setTab('workspace')}}>Abrir <ArrowUpRight size={16}/></button></TableCell></TableRow>)}</TableBody></Table>{!visible.length&&<div className="empty">Nenhum orçamento encontrado. Altere a busca ou acompanhe um novo orçamento.</div>}</div></TabsContent>
 <TabsContent value="results" className="panel-page"><div className="page-heading"><div><div className="eyebrow">RESULTADOS DA DEMONSTRAÇÃO</div><h1>Conversas que viram vendas.</h1><p>Valores registrados pelo vendedor, não recebimentos verificados.</p></div><span className="status green">Sessão atual</span></div><div className="results-grid"><article className="result-hero"><CircleDollarSign size={34}/><p>Valor marcado como recuperado</p><strong>{money(recovered.reduce((s,l)=>s+l.value,0))}</strong><span>{recovered.length} {recovered.length===1?'venda confirmada':'vendas confirmadas'} pelo vendedor</span><div className="result-rule"/><p>O resultado começa com uma conversa retomada.</p><button className="light-button" onClick={()=>{setFilter('Hoje');setTab('pipeline')}}>Ver oportunidades de hoje <ArrowUpRight size={17}/></button></article><article className="white-card"><h2>Visão das oportunidades</h2>{['Aguardando retorno','Em conversa','Recuperado','Encerrado'].map(s=><div className="bar-row" key={s}><div><span>{s}</span><b>{leads.filter(l=>l.status===s).length}</b></div><div className="bar-track"><span style={{width:`${leads.filter(l=>l.status===s).length/leads.length*100}%`}}/></div></div>)}</article></div><article className="white-card recovered-list"><h2>Vendas recuperadas</h2>{recovered.length?recovered.map(l=><div key={l.id}><span className="avatar small">{initials(l.name)}</span><span><b>{l.name}</b><small>{l.service}</small></span><strong>{money(l.value)}</strong><Check size={18}/></div>):<p>Nenhuma venda recuperada ainda. Registre o resultado de uma conversa para vê-lo aqui.</p>}</article></TabsContent>
 <TabsContent value="settings" className="panel-page"><div className="page-heading"><div><div className="eyebrow">DO JEITO DA SUA EMPRESA</div><h1>Configurações</h1><p>Defina o contexto e os limites do seu assistente.</p></div></div><form className="settings-grid" onSubmit={e=>{e.preventDefault();notify('Configurações salvas nesta sessão de demonstração.')}}><article className="white-card"><h2>Empresa e condições</h2><label className="field">Nome da empresa<input required value={company} onChange={e=>setCompany(e.target.value)}/></label><label className="field">Regras para o atendimento<textarea value={rules} onChange={e=>setRules(e.target.value)}/></label><p className="muted">Neste protótipo, as sugestões são exemplos fixos. Estas regras serão usadas pela IA na versão conectada.</p></article><article className="white-card"><h2>Intervalos de retomada</h2><p className="muted">Dias após o envio do orçamento. São lembretes para revisão, não disparos automáticos.</p><div className="intervals">{days.map((d,i)=><label className="field" key={i}>{i+1}ª tentativa<input aria-label={`Dias da tentativa ${i+1}`} type="number" min={i===0?1:days[i-1]+1} max={90} required value={d} onChange={e=>setDays(ds=>ds.map((v,j)=>i===j?Number(e.target.value):v))}/><small>dias</small></label>)}</div><div className="safety-note"><ShieldCheck size={22}/><span>Ao receber resposta, recusa ou confirmação de venda, interrompa a sequência. O acompanhamento é manual nesta versão.</span></div></article><button className="primary" type="submit">Salvar configurações <Check size={17}/></button></form></TabsContent>
 </Tabs><footer className="site-footer"><span>retoma <span>· Recuperação de orçamentos</span></span><span>Feito para retomar, não para insistir.</span></footer>{notice&&<div className="toast" role="status"><Check size={18}/>{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}>×</button></div>}
 <Dialog open={modal} onOpenChange={setModal}><DialogContent className="new-dialog"><DialogTitle>Acompanhar orçamento</DialogTitle><DialogDescription>Cadastre uma proposta já enviada. Use apenas dados fictícios nesta demonstração.</DialogDescription><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const id=Math.max(...leads.map(l=>l.id))+1;const item:Lead={id,name:String(f.get('name')),company:String(f.get('company')),service:String(f.get('service')),value:Number(f.get('value')),status:'Aguardando retorno',next:'Hoje',paused:false,messages:[{text:'Orçamento cadastrado para acompanhamento nesta demonstração.',out:true}]};setLeads(ls=>[...ls,item]);setModal(false);choose(item);setTab('workspace');notify('Orçamento adicionado à sua fila de recuperação.')}}>{[['name','Nome do cliente'],['company','Empresa do cliente'],['service','Produto ou serviço'],['value','Valor do orçamento (R$)']].map(([name,label])=><label className="field" key={name}>{label}<input name={name} required type={name==='value'?'number':'text'} min={name==='value'?'0.01':undefined} step={name==='value'?'0.01':undefined}/></label>)}<button className="primary full" type="submit">Começar acompanhamento <ArrowUpRight size={17}/></button></form></DialogContent></Dialog></div>
}
